import React, { useContext, useRef } from 'react';
import PropTypes from 'prop-types';
import { EventContext, Styled } from 'direflow-component';
import styles from './App.css';
import BridgeComp from './BridgeComp';
// import "@pharbers-node/react-nested-components"

const App = (props) => {
	const dispatch = useContext(EventContext);

	const handleClick = () => {
		const event = new Event('example-event');
		dispatch(event);
	};

	const handleNestEvent = (e) => {
		const event = new Event(e.type)
		dispatch(event);
	}

	return (
		<Styled styles={styles}>
			<div className='app'>
				<div className='top'>
					<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1280px-React-icon.svg.png" />
				</div>
				<div className='bottom'>
					<div className='header-title'>{props.componentTitle}</div>
					{ props.color &&
					<p>Color generated by Ember context: <span style={{color: props.color}}>{props.color}</span></p>
					}
					<button className='button' onClick={handleClick}>
						Emit new color event
					</button>
					<BridgeComp onEventCallback={handleNestEvent}/>
				</div>
			</div>
		</Styled>
	);
};

App.propTypes = {
	componentTitle: PropTypes.string,
	color: PropTypes.string,
};

export default App;
